In [1]:
import numpy as np

In [2]:
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])           
y = np.array([[0,0,1,1]]).T

In [3]:
np.random.seed(1)

In [24]:
def sigmoid(x):
    return 1.0/(1 + np.exp(-x))

---
两层神经网络
---
X: 输入训练集，每一行为一个样本  
y: 训练集样本标签  
layer0: 网络第一层，即输入层  
layer1: 网络第二层，即隐藏层  
syn0: 第一层权值，连接layer0和layer1  
*: 逐元素相乘element-wise  
np.dot(a, b): 若a，b为向量，则点积；若a，b均为矩阵，则矩阵相乘；若a，b一个矩阵一个向量，则矩阵乘以向量 

---

In [13]:
# initialize weights with mean of 0
syn0 = 2 * np.random.random((3,1)) - 1

for iter in range(10000):
    layer0 = X
    layer1 = sigmoid(np.dot(layer0, syn0))
    layer1_error = y - layer1
    # 误差项加权导数值 layer1_delta
    layer1_delta = layer1_error * (layer1 * (1- layer1)) # element-wise
    
    # update weights
    syn0 += np.dot(layer0.T, layer1_delta)
    if iter % 2000 == 0:
        print("layer1_error is: %s" % layer1_error)
        print("syn0 is: %s" % syn0)
print("the final output layer1 is:\n %s"%layer1)

layer1_error is: [[ -3.15074698e-03]
 [ -3.14088783e-03]
 [  1.67105277e-05]
 [  3.14580288e-03]]
syn0 is: [[  5.76010887e+00]
 [ -3.13401990e-03]
 [ -5.76012558e+00]]
layer1_error is: [[ -3.09036050e-03]
 [ -3.08087440e-03]
 [  1.60785874e-05]
 [  3.08560374e-03]]
syn0 is: [[  5.77946094e+00]
 [ -3.07426628e-03]
 [ -5.77947702e+00]]
layer1_error is: [[ -3.03331160e-03]
 [ -3.02417138e-03]
 [  1.54927080e-05]
 [  3.02872852e-03]]
syn0 is: [[  5.79809397e+00]
 [ -3.01780412e-03]
 [ -5.79810946e+00]]
layer1_error is: [[ -2.97930398e-03]
 [ -2.97048531e-03]
 [  1.49480306e-05]
 [  2.97488236e-03]]
syn0 is: [[  5.81605944e+00]
 [ -2.96434195e-03]
 [ -5.81607439e+00]]
layer1_error is: [[ -2.92807687e-03]
 [ -2.91955790e-03]
 [  1.44403568e-05]
 [  2.92380572e-03]]
syn0 is: [[  5.83340351e+00]
 [ -2.91362321e-03]
 [ -5.83341795e+00]]
the final output layer1 is:
 [[ 0.00287942]
 [ 0.00287118]
 [ 0.99998603]
 [ 0.99712471]]


---
三层神经网络
---
注意参数更新，BP神经网络

---

In [14]:
# randomly initiaize our weights with mean 0
syn0 = 2 * np.random.random((3, 4)) - 1  # (-1, 1)
syn1 = 2 * np.random.random((4, 1)) - 1

In [25]:
for j in range(60000):
    # feed forward for layer0, layer1, layer2
    layer0 = X
    layer1 = sigmoid(np.dot(X, syn0))
    layer2 = sigmoid(np.dot(layer1, syn1))
    
    # error
    layer2_error = y - layer2
    if j % 10000 == 0:
        print("Error: %s" % np.mean(np.abs(layer2_error)))
    
    # delta 误差加权导数
    layer2_delta = layer2_error * ((layer2 * ( 1- layer2)))
    
    # backward propogation
    layer1_error = layer2_delta.dot(syn1.T)
    layer1_delta = layer1_error * ((layer1 * (1 - layer1)))
    
    # updata weights
    syn1 += layer1.T.dot(layer2_delta)
    syn0 += layer0.T.dot(layer1_delta)

Error: 0.00386920107475
Error: 0.00356926330795
Error: 0.0033288778634
Error: 0.00313070058356
Error: 0.00296371270044
Error: 0.00282053651234


In [26]:
layer2

array([[ 0.00290123],
       [ 0.99734845],
       [ 0.99731685],
       [ 0.00254821]])

In [19]:
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in range(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

In [20]:
y-l2

array([[-0.0041365 ],
       [ 0.00380296],
       [ 0.00384654],
       [-0.00369094]])

In [27]:
l2

array([[ 0.0041365 ],
       [ 0.99619704],
       [ 0.99615346],
       [ 0.00369094]])